shamefullyHoist: true

allowBuilds:
  "@parcel/watcher": true
  better-sqlite3: true
  esbuild: true
  protobufjs: false
  unrs-resolver: true
  vue-demi: false

overrides:
  serialize-javascript@<=7.0.2: ">=7.0.3"

minimumReleaseAgeExclude:
  - "@vitest/coverage-v8@5.0.1"
  - "@vitest/mocker@5.0.1"
  - "@vitest/pretty-format@5.0.1"
  - "@vitest/spy@5.0.1"
  - "@vitest/ui@5.0.1"
  - "@vitest/utils@5.0.1"
  - vitest@5.0.1
