import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    POSTGRES_AZURE_DBNAME = os.getenv("POSTGRES_AZURE_DBNAME")
    POSTGRES_AZURE_HOST = os.getenv("POSTGRES_AZURE_HOST")
    POSTGRES_AZURE_USER = os.getenv("POSTGRES_AZURE_USER")
    POSTGRES_AZURE_PASSWORD = os.getenv("POSTGRES_AZURE_PASSWORD")
    AZURE_SQL_CONNECTION_STRING = os.getenv("AZURE_SQL_CONNECTION_STRING")
    MIXEDBREAD_API_KEY = os.getenv("MIXEDBREAD_API_KEY")
