apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: simonweigold/cold-flask-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: AUTH_ADDRESS
            value: backend-service
          - name: SQL_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: cold-secrets
                key: SQL_CONN_STRING
          - name: MONGODB_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: cold-secrets
                key: MONGODB_CONN_STRING
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: cold-secrets
                key: OPENAI_API_KEY
          - name: TEST
            valueFrom:
              secretKeyRef:
                name: cold-secrets
                key: TEST