apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-backend
  template:
    metadata:
      labels:
        app: staging-backend
    spec:
      containers:
        - name: staging-backend
          image: simonweigold/cold-fastapi-backend:alpha-20250303
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: SQL_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: cold-secrets
                  key: SQL_CONN_STRING
            - name: MONGODB_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: cold-secrets
                  key: MONGODB_CONN_STRING
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cold-secrets
                  key: OPENAI_API_KEY
            - name: IPINFO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cold-secrets
                  key: IPINFO_ACCESS_TOKEN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cold-secrets
                  key: JWT_SECRET
            - name: TEST
              valueFrom:
                secretKeyRef:
                  name: cold-secrets
                  key: TEST
---
apiVersion: v1
kind: Service
metadata:
  name: staging-backend-service
spec:
  selector:
    app: staging-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
