name: Trigger auto deployment for cold-web-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ alpha ]
    paths:
    - '**'
    - '.github/workflows/cold-web-app-AutoDeployTrigger-f3fef807-7070-4827-a7c2-4cb4186022f7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.COLDWEBAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COLDWEBAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COLDWEBAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: ${{ github.workspace }}/backend/Dockerfile
          registryUrl: registry.hub.docker.com
          registryUsername: ${{ secrets.COLDWEBAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COLDWEBAPP_REGISTRY_PASSWORD }}
          containerAppName: cold-web-app
          resourceGroup: cold
          imageToBuild: simonweigold/cold-flask-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


